// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBubx_NUxWxMnMccFEOTdyWIjx1C2kUjw8',
    appId: '1:15288699311:web:9c8e7ad92df1217556875a',
    messagingSenderId: '15288699311',
    projectId: 'talkychatapp-bd3ce',
    authDomain: 'talkychatapp-bd3ce.firebaseapp.com',
    storageBucket: 'talkychatapp-bd3ce.appspot.com',
    measurementId: 'G-M7STJQDBMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDouFJTgcNkklCQG9Dsuvk3-2yQ1353aWc',
    appId: '1:15288699311:android:6b208d92d2a14bad56875a',
    messagingSenderId: '15288699311',
    projectId: 'talkychatapp-bd3ce',
    storageBucket: 'talkychatapp-bd3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlJns1rtyekci3kR3fjScl7KUo9V5lpX0',
    appId: '1:15288699311:ios:182c966c511e4f1056875a',
    messagingSenderId: '15288699311',
    projectId: 'talkychatapp-bd3ce',
    storageBucket: 'talkychatapp-bd3ce.appspot.com',
    iosClientId: '15288699311-ccr9sbphgme0sgim5kp9vm1ccctrjkne.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlJns1rtyekci3kR3fjScl7KUo9V5lpX0',
    appId: '1:15288699311:ios:f11a96006d80827a56875a',
    messagingSenderId: '15288699311',
    projectId: 'talkychatapp-bd3ce',
    storageBucket: 'talkychatapp-bd3ce.appspot.com',
    iosClientId: '15288699311-s2lv6pdk68uc60bhkej82n8v1pttvb8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
